### ISSUE TITLE
If a folder is given beastiary should try to load all the files instead of raising an error

### ISSUE THREAD

**Issue by Wytamma** [Wytamma/beastiary#42]
beastiary results/B.1.617.2-Nepal/

🐙🐁 STARTING BEASTIARY 🐁🐙

Adding log files:
Traceback (most recent call last):
  File "/data/gpfs/projects/punim1654/wytamma/nepal/.beastiary-env/bin/beastiary", line 8, in <module>
    sys.exit(app())
  File "/data/gpfs/projects/punim1654/wytamma/nepal/.beastiary-env/lib64/python3.9/site-packages/typer/main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "/data/gpfs/projects/punim1654/wytamma/nepal/.beastiary-env/lib64/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/data/gpfs/projects/punim1654/wytamma/nepal/.beastiary-env/lib64/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/data/gpfs/projects/punim1654/wytamma/nepal/.beastiary-env/lib64/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/data/gpfs/projects/punim1654/wytamma/nepal/.beastiary-env/lib64/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/data/gpfs/projects/punim1654/wytamma/nepal/.beastiary-env/lib64/python3.9/site-packages/typer/main.py", line 497, in wrapper
    return callback(**use_params)  # type: ignore
  File "/data/gpfs/projects/punim1654/wytamma/nepal/.beastiary-env/lib64/python3.9/site-packages/beastiary/cli.py", line 59, in main
    trace = add_trace(
  File "/data/gpfs/projects/punim1654/wytamma/nepal/.beastiary-env/lib64/python3.9/site-packages/beastiary/api/core.py", line 39, in add_trace
    raise FileNotFoundError(errno.ENOENT, os.strerror(errno.ENOENT), trace_in.path)
FileNotFoundError: [Errno 2] No such file or directory: PosixPath('results/B.1.617.2-Nepal')

**Comment by Wytamma** [comment]
Use `beastiary results/B.1.617.2-Nepal/*`
